### ISSUE TITLE
Query with a partition key

### ISSUE THREAD

**Issue by purplekrayons** [jupitern/cosmosdb#15]
It is Microsoft's stated intent to deprecate the ability to create collections without defining a partition key. They advised that you cannot achieve elastic scale-ability with the cosmos service if you do not use partition keys, thus it would defeat the purpose of using Cosmos.

Currently, if you create collections with a partition key, the only way to execute a query is by passing `true` to the `find()` method so as to execute it as a cross-partition query (which sets the header `x-ms-documentdb-query-enablecrosspartition` to `True`.

However, cross-partition queries naturally consume more RU's (resource units). In simple situations where you know what the partition key will be, I propose being able to pass the partition value and setting the `x-ms-documentdb-partitionkey` header when executing the query.

This will enable a user to refine their queries and ultimately achieve better efficiency with their applications.

However, I have an issue --- yesterday I submit a PR where I alter the way `->setPartitionKey()` works in order to support saving records against collections with a nested partition key value. This works because the user would pass the document as part of that query instance, thus we can iterate through it to find the partition value.

In the case of a query, where the user doesn't have the document object, we would have nothing to iterate through to get the partition value.

Based on this, I believe we have three options:

1. Use the `find()` method to pass known partition values as a string.
2. Rework the `->setPartitionKey()` so that users must pass the partition value upfront, rather than having this library try and find it from the document object --- since users are the ones passing the document, they will inherently already know the value.
3. Create a new method, something like `partitionValue()` to accept a known partition value.

Which method do you feel would be best?

I'll note that Method #1 could be something simple like:

Modify **query()** method in **[CosmosDb.php](https://github.com/jupitern/cosmosdb/blob/master/src/CosmosDb.php#L191)**

```php
if ($isCrossPartition === true) {
    $headers['x-ms-documentdb-query-enablecrosspartition'] = 'True';
}

if (isset($isCrossPartition) && is_string($isCrossPartition)) {
    $headers['x-ms-documentdb-partitionkey'] = '["'.$isCrossPartition.'"]';
}
```

**Cross-partition query:**

```php
$params["@formId"] = $formId;

$res = \Jupitern\CosmosDb\QueryBuilder::instance()
    ->setCollection($collection)
    ->select("*")
    ->where("c.id = @formId")
    ->params($params)
    ->find(true)    # enable cross-partition query
    ->toArray();
```

**Partition specific query:**

```php
$params["@formId"] = $formId;

$res = \Jupitern\CosmosDb\QueryBuilder::instance()
    ->setCollection($collection)
    ->select("*")
    ->where("c.id = @formId")
    ->params($params)
    ->find('enroll')    # pass the known partition key to avoid cross-partition queries
    ->toArray();
```

Method #2 would probably alter the way others are using this library, so i'm not sure how I feel about that.

Method #3 might be the best option here?

What are your thoughts?

**Comment by purplekrayons** [comment]
I have submit a pull request implementing method 3; please refer to PR #16

**Comment by jupitern** [comment]
Hi,
great work. I think the new method is the best best.
thanks
