### ISSUE TITLE
Pagination not handled

### ISSUE THREAD

**Issue by ElvenSpellmaker** [jupitern/cosmosdb#21]
I see inside the code that pagination isn't handled because you set the max size to `-1`.

However CosmosDB has a 4MB maximum packet size and will automatically paginate after that size.

I've managed to get some hack code together locally for now inside this module, but it'd be nice to natively support this.

I did something like this:

Firstly modify `request()` to return the full Guzzle response in `CosmosDb`:
```php
return $response->getBody()->getContents();
```
to:
```php
return $response;
```
Then I modify all functions inside `CosmosDb` to unwrap the Guzzle request, for example in the `getDatabase` method:
```php
return $this->request("/dbs/{$rid_id}", "GET", $headers);
```
to:
```php
return $this->request("/dbs/{$rid_id}", "GET", $headers)->getBody()->getContents();
```

Then I modify the `query()` method to support the pagination and return an array of result objects (excuse the `goto` used here, it's an easy way of achieving this quickly):
```php
$results = [];
...
retry:
try {
    $result = $this->request("/dbs/{$rid_id}/colls/{$rid_col}/docs", "POST", $headers, $query);
}
...
$results[] = $result->getBody()->getContents();

if ($result->getHeader('x-ms-continuation') !== [])
{
    $token = $result->getHeader('x-ms-continuation');

    $headers['x-ms-continuation'] = $token;

    goto retry;
}

return $results;
```

And then finally I changed `toArray` in the `QueryBuilder` to stitch together multiple result sets:
```php
    public function toArray($arrayKey = null)
    {
        $results = [];

        foreach ($this->response as $res)
        {
            $res = json_decode($res);
            $docs = $res->Documents ?? [];

            if ($this->multipleResults) {
                $docs = $arrayKey != null ? array_combine(array_column($docs, $arrayKey), $docs) : $docs;
            } else {
                $docs = isset($docs[0]) ? $docs[0] : null;
            }

            $results = array_merge($results, $docs);
        }

        return $results;
    }
```

This is a half-baked solution as it doesn't handle all the other methods like `toObject` etc, but it works for what I need.

**Comment by jupitern** [comment]
Hi,
Can you submit a PR with a complete solution? thanks

**Comment by rajata07** [comment]
@ElvenSpellmaker Are you working on submitting a PR otherwise I can take over this issue? Please let me know.

**Comment by ElvenSpellmaker** [comment]
Hey @rajata07, I wasn't working on a PR as I managed to hack the library to do what I needed and it's really not a clean solution currently.

**Comment by gbdeboer** [comment]
Hey @jupitern @ElvenSpellmaker I've created a fix and pull request based on your comments above. See #27.
