### ISSUE TITLE
QueryBuilder delete() and deleteAll() probably contain a bug with partitionkey lookup

### ISSUE THREAD

**Issue by djm81** [jupitern/cosmosdb#23]
Hi,

I just found after some errors display that the **delete()** and **deleteAll()** methods didn't work.
The issue is the following code within QueryBuilder.php in lines 408/409 and 431/432:

```php
$select = $this->fields != "" ? $this->fields : "c._rid" . ($this->partitionKey != null ? ", c.{$this->findPartitionValue($document, true)}" : "");
```

The variable $document doesn't exist at this point the methods, probably a copy-paste issue from the other methods where a $document object has been provided.

The following possible fix worked for me:

```php
$select = $this->fields != "" ?
            $this->fields : "c._rid" . ($this->partitionKey != null ? ", c." . $this->partitionKey : "");
```

This if course will not work for nested partition keys which I actually don't use, so maybe you have another solution which also supports nested partition keys with delete() and deleteAll().

Thanks for checking.

**Comment by djm81** [comment]
**Expected behaviour:**

return result of **true** or **false**

**Actual behaviour:** 

`Notice: Undefined variable: document in ...\backend\vendor\jupitern\cosmosdb\src\QueryBuilder.php on line 410

Fatal error: Uncaught TypeError: Argument 1 passed to Jupitern\CosmosDb\QueryBuilder::findPartitionValue() must be an object, null given, called in ...\backend\vendor\jupitern\cosmosdb\src\QueryBuilder.php on line 410 and defined in ...\backend\vendor\jupitern\cosmosdb\src\QueryBuilder.php:336 Stack trace: #0 ...\backend\vendor\jupitern\cosmosdb\src\QueryBuilder.php(410): Jupitern\CosmosDb\QueryBuilder->findPartitionValue(NULL, true) #1 test.php(32): Jupitern\CosmosDb\QueryBuilder->delete() #2 {main} thrown in ...\backend\vendor\jupitern\cosmosdb\src\QueryBuilder.php on line 336`

**Comment by jupitern** [comment]
Hi,
Can you submit a PR to fix this bug?

**Comment by djm81** [comment]
Hi @jupitern,

sorry for my late response. Sure I'll do so, however I guess I would need to create a branch first and then create the PR from that? If so, I'm not able to create a branch.

Maybe you have an idea how it would work?

Thanks,
Dom

**Comment by mrahmadt** [comment]
Hello

PR created https://github.com/jupitern/cosmosdb/pull/25

**Comment by scadox** [comment]
Hi @mrahmadt , thank you for this fix i have too this problem. If is possible generate new tag version for prevent use origin master.

I wish you a good day and congratulations on this package I like it

**Comment by danieldespainTLS** [comment]
When I install from composer, the code still has this bug.  Glad I was able to find the fix here.  Thanks for this library; it's awesome!
