### ISSUE TITLE
Fatal error: Uncaught Exception: BadRequest : Message: {"Errors":["The partition key supplied in x-ms-partitionkey header has fewer components than defined in C:\wamp64\www\src\QueryBuilder.php on line 392

### ISSUE THREAD

**Issue by dakerse** [jupitern/cosmosdb#24]
Hi,

I get this message from Azure when I try to insert a document in my collection.

Fatal error: Uncaught Exception: BadRequest : Message: {"Errors":["The partition key supplied in x-ms-partitionkey header has fewer components than defined in C:\wamp64\www\src\QueryBuilder.php on line 392

Exception: BadRequest : Message: {"Errors":["The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection."]} ActivityId: cb6dfc3a-ff43-4c06-9ee3-65ff7328f68b, Request URI: /apps/5960566d-44be-48a9-b4c3-d5556348544f/services/4e5fcb9a-a912-4dc0-a189-f72fed7ed011/partitions/cef0ac47-17b2-4b2c-ba72-41b00079330d/replicas/132425316537653851p/, RequestStats: RequestStartTime: 2020-08-24T14:57:27.3252512Z, RequestEndTime: 2020-08-24T14:57:27.3452328Z, Number of regions attempted:1 ResponseTime: 2020-08-24T14:57:27.3452328Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-francecentral1-fd5.documents.azure.com:14051/apps/5960566d-44be-48a9-b4c3-d5556348544f/services/4e5fcb9a-a912-4dc0-a189-f72fed7ed011/partitions/cef0ac47-17b2-4b2c-ba72-41b00079330d/replicas/132425316537653851p/, LSN: 1, GlobalCommittedLsn: 1, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 1001, RequestCharge: 0, ItemLSN: -1, SessionToken: 1, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Create , SDK: Microsoft.Azure.Documents.Common/2.11.0 in C:\wamp64\www\src\QueryBuilder.php on line 392

I don't know how to solve this problem. I attached my code.

Thanks

![Capture](https://user-images.githubusercontent.com/70153873/91063678-94f21a80-e62e-11ea-9264-527ce49276a4.PNG)

**Comment by jupitern** [comment]
I guess partition key "id" does not exist. looks like you created partition key type
