### ISSUE TITLE
Non cross partition queries are now deprecated

### ISSUE THREAD

**Issue by tonila** [jupitern/cosmosdb#3]
Azure has deprecated non cross partition queries.

> We lowered the minimum throughput for partitioned containers to 400 RU/s, removing the only drawback partitioned containers had. 
> 
> We are planning to deprecate ability to create non-partitioned containers, as they do not allow you to scale elastically. If for some reason you still need a container without partition key, you can use our SDKs to create one. 
> 
> Please contact us if you have questions or concerns.

header `x-ms-query-enable-crosspartition: true` is required to enable cross partition queries.

see:
https://docs.microsoft.com/en-us/rest/api/cosmos-db/querying-cosmosdb-resources-using-the-rest-api

**Comment by jupitern** [comment]
I will make a new realese between today and tomorrow with that add support to that nd other things.
The header x-ms-query-enable-crosspartition is only mandatory if in your query you don't filter by the partition field.

**Comment by jupitern** [comment]
Hi,
Maybe you can help me. I have created a development branch with a few changes to support cross partition queries and reduce the need to always select the collection before each query. 

Take a look at the file:
https://github.com/jupitern/cosmosdb/blob/development/examples/example1.php

When I make a query with the partition field present in where clause woks fine:

$users = \Jupitern\CosmosDb\QueryBuilder::instance()
    ->setDatabase($db)
    ->setCollection($collection)
    ->select("c.id, c.name, c.age")        // always use "c" as collection name
    ->where("c.age = 30 and c.collectiontype = 'user'")
    ->order("c.name asc")
    ->limit(10)
    ->findAll() // pass boolean to indicate if query is cross partition
    ->toObject();

When I make a query without the partition field present but do not use order or limit works fine:

$users = \Jupitern\CosmosDb\QueryBuilder::instance()
    ->setDatabase($db)
    ->setCollection($collection)
    ->select("c.id, c.name, c.age")        // always use "c" as collection name
    ->where("c.age = 30")
    ->findAll(true) // pass boolean to indicate if query is cross partition
    ->toObject();

When I make a query without the partition field present and use order or limit i get the error 
"The provided cross partition query can not be directly served by the gateway"

$users = \Jupitern\CosmosDb\QueryBuilder::instance()
    ->setDatabase($db)
    ->setCollection($collection)
    ->select("c.id, c.name, c.age")        // always use "c" as collection name
    ->where("c.age = 30")
    ->findAll(true) // pass boolean to indicate if query is cross partition
    ->toObject();

**Comment by tonila** [comment]
Hi,

I tested this a while and has same results as you did. 

I had no idea what to do, but to Google violenty. It also took a while, but I finally managed to found an explanation.
https://stackoverflow.com/questions/50240232/cosmos-db-rest-api-order-by-with-partitioning

**Comment by TCB13** [comment]
@tonila thank you for the link. I believe this is now closed by the changes at https://github.com/jupitern/cosmosdb/pull/9. Can you provide some feedback?
